### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by stratosgear** [zhaofengli/attic#208]
Hello all, 

I have a very weird issue.  For a while I had atticd succesfully installed and I was using it.

But once I decided to remove it, and updated my substituters, it seems that now rebuilding my flake I always get:

```
sudo nixos-rebuild switch --flake /home/stratos/ultragear/#iocaine
building the system configuration...
downloading 'https://attic.gerakakis.net/ultracache/nix-cache-info'^CTraceback (most recent call last):
  File "/run/current-system/sw/bin/ultragear", line 878, in <module>
    main()
  File "/run/current-system/sw/bin/ultragear", line 874, in main
    fire.Fire(name="ultragear", component=UG)
  File "/nix/store/df4jmlp6bbll0w4l7va39x82j35pk1sw-python3-3.12.6-env/lib/python3.12/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/df4jmlp6bbll0w4l7va39x82j35pk1sw-python3-3.12.6-env/lib/python3.12/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/df4jmlp6bbll0w4l7va39x82j35pk1sw-python3-3.12.6-env/lib/python3.12/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/run/current-system/sw/bin/ultragear", line 755, in update
    run(f"sudo nixos-rebuild switch {cacheOpt}--flake {ULTRAGEAR}/#{currentHost}")
  File "/run/current-system/sw/bin/ultragear", line 125, in run
    out = subprocess.run(
          ^^^^^^^^^^^^^^^
  File "/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/lib/python3.12/subprocess.py", line 1196, in communicate
    stdout = self.stdout.read()
             ^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

That I have to CTLR+C to get out off, since the https://attic.gerakakis.net/ultracache/nix-cache-info is not available anymore (that's where I was hosting atticd)

I have completely removed my `~/.config/nix/nix.conf`:

```
➜  cat ~/.config/nix/nix.conf
cat: /home/stratos/.config/nix/nix.conf: No such file or directory

~ via  
✗  
```

My `/etc/nix/nix.conf` contains **no** references to `attic.gerakakis.net` binary caches:

```
✗  cat /etc/nix/nix.conf                                                                             
# WARNING: this file is generated from the nix.* options in
# your NixOS configuration, typically
# /etc/nixos/configuration.nix.  Do not edit it!
allowed-users = root stratos
auto-optimise-store = true
builders = 
cores = 0
experimental-features = nix-command flakes
http-connections = 50
keep-derivations = true
keep-outputs = true
log-lines = 50
max-jobs = auto
require-sigs = true
sandbox = relaxed
sandbox-fallback = false
substituters = https://cache.nixos.org https://nixoscache.gerakakis.net https://ultragear.cachix.org
system-features = nixos-test benchmark big-parallel kvm
trusted-public-keys = cache.nixos.org-1:6NCHdD59X4PMQFGspcDShjY= ultragear.cachix.org-1:fIBH3wFNWTVWBcn4E2Rdr/t6boV52KavU=
trusted-substituters = 
trusted-users = root stratos
warn-dirty = false
extra-platforms = aarch64-linux i686-linux
extra-sandbox-paths = /run/binfmt /nix/store/hlf1icv45d8dsgfhrbvhinpby68z0qz5-qemu-aarch64-binfmt-P-x86_64-unknown-linux-musl
extra-experimental-features = nix-command flakes
```

I have rebooted multiple times and I have removed `~/.cache/nix` and `/root/.cache/nix` directories.

My flake.nix (and my whole git repo that hosts all my nix files) **does not** contain any references to any `attic` strings!

I have no idea why my system configuration **still** tries to contact `attic.gerakakis.net`.

I am now forced to allways use `--option binary-caches https://cache.nixos.org/` in all my nix commands... :(

Any ideas where else to look to properly uninstall attic...?

Thanks a lot!!!

**Comment by stratosgear** [comment]
Apologies for the noise!!!!

I just got a useful reply from the nix discord channel where I had posted a question there!

Issue was a rogue `substituters = https://attic.gerakakis.net/ultracache` in my `/root/.config/nix.nix.conf` file... :(
