### ISSUE TITLE
No such file or directory - while creating httpclient using reqwest

### ISSUE THREAD

**Issue by eswar2001** [zhaofengli/attic#88]
While running attic client in jenkins agent/slave `[jenkins/jnlp-slave:latest-jdk11]` , getting this error.

Note: Installed it using nix
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', client/src/api/mod.rs:249:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

With RUST_BACKTRACE=full
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', client/src/api/mod.rs:249:10
stack backtrace:
   0:     0x56444dd15751 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h63269f8f54853ab3
   1:     0x56444dd41d7f - core::fmt::write::h250dd3fc350bbada
   2:     0x56444dd22491 - std::io::Write::write_fmt::h0fd841d7fefd9302
   3:     0x56444dd15555 - std::sys_common::backtrace::print::hc99c547a903c74f7
   4:     0x56444dd2a577 - std::panicking::default_hook::{{closure}}::h5bbb3f780658c969
   5:     0x56444dd2a2e2 - std::panicking::default_hook::h1946653929a625f2
   6:     0x56444dd2a94c - std::panicking::rust_panic_with_hook::h8216316e1970270b
   7:     0x56444dd15a47 - std::panicking::begin_panic_handler::{{closure}}::h45b7865605f63cc8
   8:     0x56444dd15836 - std::sys_common::backtrace::__rust_end_short_backtrace::h2efe3248368b98bf
   9:     0x56444dd2a672 - rust_begin_unwind
  10:     0x56444d7aa6a3 - core::panicking::panic_fmt::h90a1387c4eee835e
  11:     0x56444d7aa423 - core::result::unwrap_failed::h45eef99f88d7b5bc
  12:     0x56444d7defb3 - attic::api::ApiClient::from_server_config::h44fe2576e7557304
  13:     0x56444d852ef1 - attic::command::use::run::{{closure}}::h498e2cf9c27ce152
  14:     0x56444d84a8d4 - attic::cli::run::{{closure}}::h83415be7676fb6cf
  15:     0x56444d8441fb - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h51eedbd7a9f77a02
  16:     0x56444d829c94 - tokio::runtime::context::BlockingRegionGuard::block_on::h57538c86f33c8dc0
  17:     0x56444d868467 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hb5173b5ab6a7e142
  18:     0x56444d8158fa - tokio::runtime::runtime::Runtime::block_on::h94f8de7303fdcbe2
  19:     0x56444d7cd1e8 - attic::main::h6036c228c0e9f43c
  20:     0x56444d85dec3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h743d24d738f85d20
  21:     0x56444d85e19d - std::rt::lang_start::{{closure}}::hc12bad0c6a1d71c0
  22:     0x56444dd119b7 - std::rt::lang_start_internal::h8ab23524475b2279
  23:     0x56444d7cd2d5 - main
  24:     0x7f2d8971aace - __libc_start_call_main
  25:     0x7f2d8971ab89 - __libc_start_main@@GLIBC_2.34
  26:     0x56444d7aad15 - _start
  27:                0x0 - <unknown>
```

**Comment by eswar2001** [comment]
Found the Issue , because of `SSL_CERT_FILE` env. post unsetting no issues.
